[package]
name = "brk_mcp"
description = "A bridge for LLMs to access BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
axum = { workspace = true }
brk_rmcp = { version = "0.8.0", features = [
    "transport-worker",
    "transport-streamable-http-server",
] }
tracing = { workspace = true }
minreq = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_json"]
