[package]
name = "brk_website"
description = "Standalone website server for BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
include = ["src/**/*", "website/**/*", "examples/**/*", "Cargo.toml", "README.md"]

[dependencies]
axum = { workspace = true }
include_dir = "0.7"
importmap = { version = "0.3.1", features = ["embedded"] }
tracing = { workspace = true }

[dev-dependencies]
brk_logger = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tower-layer = { workspace = true }
