[package]
name = "brk_types"
description = "Structs used throughout BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
bitcoin = { workspace = true }
brk_error = { workspace = true }
byteview = { workspace = true }
derive_deref = { workspace = true }
itoa = "1.0.17"
jiff = { workspace = true }
num_enum = "0.7.5"
rapidhash = "4.2.0"
ryu = "1.0.22"
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
strum = { version = "0.27", features = ["derive"] }
vecdb = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
