[package]
name = "brk_traversable"
description = "Traits for Vecs structs throughout BRK"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[features]
derive = ["brk_traversable_derive"]
pco = ["vecdb/pco"]
zerocopy = ["vecdb/zerocopy"]
lz4 = ["vecdb/lz4"]
zstd = ["vecdb/zstd"]

[dependencies]
brk_types = { workspace = true }
brk_traversable_derive = { workspace = true, optional = true }
vecdb = { workspace = true }
