[package]
name = "brk_client"
description = "A BRK API client"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
brk_types = { workspace = true }
minreq = { workspace = true }
serde = { workspace = true }
