[package]
name = "brk_store"
description = "A thin wrapper around fjall"
keywords = ["store", "fjall"]
categories = ["database"]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
brk_error = { workspace = true }
brk_types = { workspace = true }
byteview_f2 = { version = "=0.6.1", package = "byteview" }
byteview_f3 = { version = "0.9.1", package = "byteview" }
fjall2 = { workspace = true }
fjall3 = { workspace = true }
rustc-hash = { workspace = true }
